name: Tag AWS Accounts 

on:
  workflow_dispatch:
    inputs:

      Resource_id:             #Mandatory parameter : Resourceid of the Account created
        required: true
      
      
      tagAccountRouteDomain:
        type: choice
        description: Select  ACCOUNT_ROUTE_DOMAIN_TAG
        options:  #Change to provide inputs for Account Tag
        
          - "Key=ACCOUNT_ROUTE_DOMAIN_TAG,Value=sharednonprod"
          - "Key=ACCOUNT_ROUTE_DOMAIN_TAG,Value=sharedprod"
        

      tagRouteDomain:
        type: choice
        description: Select  route_domain_tag
        options:  
        
          - "Key=route-domain,Value=aws3sharednonprod"
          - "Key=route-domain,Value=aws3sharedprod"

          
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
        
env: 
  AWS_REGION : eu-west-2 #Change to reflect your Region


jobs:
  AssumeRoleAndApplyTags:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::207644714085:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}
      - name: Execute Tagging cli
        run: |
          aws organizations tag-resource --resource-id ${{ github.event.inputs.Resource_id }} --tags ${{ github.event.inputs.tagAccountRouteDomain }}
          aws organizations tag-resource --resource-id ${{ github.event.inputs.Resource_id }} --tags ${{ github.event.inputs.tagRouteDomain }}         
      # - name: Execute Tagging cli 2
      #   run: |
      #     aws organizations tag-resource --resource-id ${{ github.event.inputs.Resource_id }} --tags ${{ github.event.inputs.tagRouteDomain }}
